version: '3.3'
services:
  bitcoind:
    image: polar/bitcoind:0.18.0
    container_name: builder-bitcoind
    build:
      context: ./bitcoind
      args:
        - BITCOIN_VERSION=0.18.0
    # Note: need to escape the dollar sign ($$) in rpcauth. there is only one in the actual password
    command: bitcoind
      -server=1
      -regtest=1
      -rpcauth=kiteuser:d81315a082bcf36bcdcd640e816566f3$$a7a42c95772b9e7461f016a8c797f5729b494ad569555aea28f5c42ee2b3fcda
      -debug=0
      -zmqpubrawblock=tcp://0.0.0.0:28334
      -zmqpubrawtx=tcp://0.0.0.0:28335
      -txindex=1
      -dnsseed=0
      -upnp=0
      -rpcbind=0.0.0.0
      -rpcallowip=0.0.0.0/0
    volumes:
      - ${PWD}/_data/bitcoind:/home/bitcoin/.bitcoin
    expose:
      - '18443' # RPC
      - '18444' # p2p
      - '28334' # ZMQ blocks
      - '28335' # ZMQ txns
    ports:
      - '18443:18443' # RPC
      - '28334:28334' # ZMQ blocks
      - '28335:28335' # ZMQ txns

  alice:
    image: polar/lnd:0.7.1-beta
    container_name: builder-lnd
    build:
      context: ./lnd
      args:
        - LND_VERSION=0.7.1-beta
    command: wait-for-it bitcoind:18443 -- lnd
      --noseedbackup
      --tlsextradomain=lnd
      --listen=0.0.0.0:9735
      --rpclisten=0.0.0.0:10009
      --restlisten=0.0.0.0:8080
      --bitcoin.active
      --bitcoin.regtest
      --bitcoin.node=bitcoind
      --bitcoind.rpchost=bitcoind
      --bitcoind.rpcuser=kiteuser
      --bitcoind.rpcpass=kitepass
      --bitcoind.zmqpubrawblock=tcp://bitcoind:28334
      --bitcoind.zmqpubrawtx=tcp://bitcoind:28335
    restart: always
    volumes:
      - ${PWD}/_data/lnd/alice:/home/lnd/.lnd
    expose:
      - '10000' # gRPC
      - '8080' # REST
      - '9735' # p2p
    ports:
      - '11001:10000' # gRPC
      - '8001:8080' # REST
      - '9001:9735' # p2p
